#!/bin/zsh
alias zshrc="nano $ZSH_DIR/zshrc"
alias clear="clear ; ISFIRSTCMD=1"
alias rs="clear ; exec zsh"
alias ls="ls --color=never"
alias cb="cd $OLDPWD"
alias zos="zopt -w $2"
alias zog="zopt -r $2"